INSERT INTO city (name, state, country) VALUES
('Indore', 'Madhya Pradesh', 'India'),
('Bhopal', 'Madhya Pradesh', 'India'),
('Mumbai', 'Maharashtra', 'India'),
('Bangalore', 'Karnataka', 'India'),
('Hyderabad', 'Telangana', 'India');

INSERT INTO person (name, age, city_id) VALUES
('Rohan Malhotra', 27, 4),
('Amit Sharma', 25, 1),
('Kavya Reddy', 22, 5),
('Priya Desai', 26, 3),
('Deepak Rawat', 33, 2),
('Snehal Patwardhan', 31, 4),
('Rahul Jain', 35, 1),
('Sai Kiran', 24, 5),
('Shruti Naik', 24, 3),
('Tarun Tiwari', 36, 2),
('Komal Goyal', 25, 3),
('Ananya Iyer', 23, 4),
('Rohit Verma', 30, 1),
('Ravi Teja', 34, 5),
('Manish Shah', 38, 3),
('Meghana Kulkarni', 24, 4),
('Ankit Yadav', 24, 1),
('Bhavya Shekar', 27, 5),
('Pooja Patel', 28, 1),
('Rakesh Kulkarni', 40, 3),
('Pallavi Joshi', 29, 4),
('Kunal Thakur', 34, 2),
('Ajay Kumar', 35, 5),
('Neha Gupta', 22, 1),
('Divya Nair', 26, 4),
('Omkar Joshi', 29, 3),
('Lakshmi Narayan', 41, 5),
('Kiran Malviya', 31, 1),
('Suresh Rao', 45, 4),
('Sumanth Rao', 28, 5),
('Vikas Mishra', 34, 1),
('Siddhi More', 22, 3),
('Harsha Gowda', 33, 4),
('Rashmi Joshi', 28, 2),
('Pooja Chandra', 26, 5),
('Aarti Bansal', 27, 3),
('Ritu Singh', 26, 1),
('Aditya Soni', 21, 2),
('Prakash Shetty', 39, 4),
('Nitin Patil', 31, 3),
('Nikhil Varma', 30, 5),
('Sonal Mehta', 27, 1),
('Vishal Pawar', 35, 3),
('Arjun Khan', 29, 2),
('Karthik Reddy', 28, 4),
('Swathi Menon', 23, 5),
('Mohit Saxena', 32, 2),
('Nisha Ali', 23, 2),
('Isha Choudhary', 25, 2),
('Sneha Kapoor', 27, 2);
